spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://${db.server}/postgres
    username: ${db.username}
    password: ${db.secret}

security:
  strength: 10

logging:
  level:
    root: INFO

